### PR TITLE
Fix icon links

### LINKED ISSUE #2: Missing Icons
The icons appear to be missing from this theme but work on the Seti theme,

### PR DESCRIPTION
**Pull request by javakat**
Changing the icon links like so will pull down the proper icons into Atom. Fixes #2, #3.

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
What's holding this back? Would like to use this theme!

**Comment by javakat** [comment]
Never heard back from @jesseweed. Pretty sure I removed all of the personal changes, so it shouldn't be a contestable PR...but sometimes dev life gets busy.

**Comment by Leeds-eBooks** [comment]
Ah ok. I've fixed this for myself by just installing https://atom.io/packages/file-icons, so I guess that might be why no one else has asked about this for a while.

**Comment by javakat** [comment]
Thanks for mentioning that. Hopefully people will come here and see that, and then they'll have an answer either way. :)

**Comment by jesseweed** [comment]
Hey sorry guys! I kind of forgot about this theme :)

**Pull request merged**
